from student import Student, Topic
from study_planner import StudyPlanner


def get_integer_input(prompt, minimum=None, maximum=None):
    while True:
        try:
            value = int(input(prompt))

            if minimum is not None and value < minimum:
                print(f"Please enter a value of at least {minimum}.")
                continue

            if maximum is not None and value > maximum:
                print(f"Please enter a value no greater than {maximum}.")
                continue

            return value

        except ValueError:
            print("Please enter a valid number.")


def get_float_input(prompt, minimum=None, maximum=None):
    while True:
        try:
            value = float(input(prompt))

            if minimum is not None and value < minimum:
                print(f"Please enter a value of at least {minimum}.")
                continue

            if maximum is not None and value > maximum:
                print(f"Please enter a value no greater than {maximum}.")
                continue

            return value

        except ValueError:
            print("Please enter a valid number.")


def main():
    print("=" * 45)
    print("              STUDYSENSE AI")
    print("=" * 45)

    student_name = input("\nStudent name: ").strip()

    available_minutes = get_integer_input(
        "Available study time today (minutes): ",
        minimum=1
    )

    student = Student(
        name=student_name,
        available_study_minutes=available_minutes
    )

    topic_count = get_integer_input(
        "\nHow many topics do you want to study? ",
        minimum=1
    )

    for index in range(1, topic_count + 1):
        print(f"\n--- Topic {index} ---")

        topic_name = input("Topic name: ").strip()

        mastery = get_float_input(
            "Current mastery (0-100): ",
            minimum=0,
            maximum=100
        )

        difficulty = get_integer_input(
            "Difficulty (1-10): ",
            minimum=1,
            maximum=10
        )

        days_to_exam = get_integer_input(
            "Days until exam: ",
            minimum=0
        )

        topic = Topic(
            name=topic_name,
            mastery=mastery,
            difficulty=difficulty,
            days_to_exam=days_to_exam
        )

        student.add_topic(topic)

    planner = StudyPlanner()

    study_plan = planner.create_plan(student)

    print("\n" + "=" * 45)
    print(f"       STUDY PLAN FOR {student.name.upper()}")
    print("=" * 45)

    print(
        f"\nAvailable Study Time: "
        f"{student.available_study_minutes} minutes\n"
    )

    for index, item in enumerate(study_plan, start=1):
        print(f"{index}. {item['topic']}")
        print(f"   Priority: {item['priority']}")
        print(f"   Recommended Time: {item['minutes']} minutes")
        print()

    print("=" * 45)
    print("Plan generated by StudySense AI")
    print("=" * 45)


if __name__ == "__main__":
    main()